import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Fusion PDF",
  description: "Generated by <a href='https://baba-komi-marcel.vercel.app'>BABA Marcel</a>",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={` antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
